"""ON CASCADE added

Revision ID: 5289501cb6d0
Revises: 09d03f6b6f8b
Create Date: 2024-06-24 00:41:40.846739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5289501cb6d0'
down_revision: Union[str, None] = '09d03f6b6f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.drop_constraint('documents_project_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint('project_participants_project_id_fkey', 'project_participants', type_='foreignkey')
    op.create_foreign_key(None, 'project_participants', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_participants', type_='foreignkey')
    op.create_foreign_key('project_participants_project_id_fkey', 'project_participants', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_project_id_fkey', 'documents', 'projects', ['project_id'], ['project_id'])
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    # ### end Alembic commands ###
