name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      POSTGRES_DB: test_db
      TEST_DATABASE_URL: postgresql://postgres@localhost/test_db
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_HOST_AUTH_METHOD: trust
      SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ALGORITHM: HS256
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: "myapp-documents-bucket"
      AWS_DEFAULT_REGION: "eu-central-1"

    services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
          options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Pipenv
        run: python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies with Pipenv
        run: |
          cp ./dependencies/Pipfile .
          cp ./dependencies/Pipfile.lock .

      - name: Install dependencies with Pipenv
        run:
          pipenv install --deploy --dev --ignore-pipfile

      - name: Code formatting check
        run: |
          pipenv run black .

      - name: Linting/code-style check
        run: |
          pipenv run flake8 .

      - name: Create test database
        run: |
          psql $TEST_DATABASE_URL -f ./app/sql/database.sql

      - name: Running tests
        run: |
          pipenv run pytest --disable-warnings --capture=no