name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      DATABASE_URL: postgresql://postgres@localhost/test_db

    services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
          options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dependencies/requirements.txt

      - name: Code formatting check
        run: black --check .

      - name: Linting/code-style check
        run: flake8 .

      - name: Running tests
        run: pytest