name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      POSTGRES_DB: test_db
      DATABASE_URL: postgresql://postgres@localhost/test_db
      POSTGRES_HOST_AUTH_METHOD: trust

    services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
          options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Pipenv
        run: python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies with Pipenv
        working-directory: dependencies
        run: pipenv install --deploy --ignore-pipfile

      - name: Code formatting check
        run: pipenv install black
          pipenv shell
          black



      - name: Linting/code-style check
        run: pipenv install flake8
          pipenv shell
          flake8


      - name: Running tests
        run: pipenv install pytest
          pytest
